# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/hannesbreit"

[social.params]
icon = "brand-github"


[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/hannes-breitfeld"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "xing"
name = "Xing"
url = "https://www.xing.com/profile/Hannes_Breitfeld"

[social.params]
icon = "brand-xing"